//! Cross-format conformance tests using ImageMagick-generated fixtures.
//!
//! All fixtures encode the same 8x8 image with red/green/blue/white quadrants.
//! Tests verify each format decodes without error, produces correct dimensions,
//! and (where applicable) exact pixel match against P6 binary PPM reference.
//!
//! ImageMagick applies colorspace transforms for grayscale and HDR output,
//! so those are tested for reasonable values rather than exact match.

use enough::Unstoppable;
use zenbitmaps::*;

fn fixture(name: &str) -> Vec<u8> {
    let path = format!("tests/fixtures/{name}");
    std::fs::read(&path).unwrap_or_else(|e| panic!("failed to read {path}: {e}"))
}

fn reference_rgb8() -> Vec<u8> {
    let data = fixture("p6_binary.ppm");
    let decoded = decode(&data, Unstoppable).unwrap();
    assert_eq!((decoded.width, decoded.height), (8, 8));
    assert_eq!(decoded.layout, PixelLayout::Rgb8);
    decoded.pixels().to_vec()
}

// ══════════════════════════════════════════════════════════════════════
// PNM family — all decode correctly, P3/P6 match exactly
// ══════════════════════════════════════════════════════════════════════

#[test]
fn fixture_p1_ascii_pbm() {
    let data = fixture("p1_ascii.pbm");
    let decoded = decode(&data, Unstoppable).unwrap();
    assert_eq!((decoded.width, decoded.height), (8, 8));
    assert_eq!(decoded.layout, PixelLayout::Gray8);
    assert!(decoded.pixels().iter().all(|&p| p == 0 || p == 255));
}

#[test]
fn fixture_p2_ascii_pgm() {
    let data = fixture("p2_ascii.pgm");
    let decoded = decode(&data, Unstoppable).unwrap();
    assert_eq!((decoded.width, decoded.height), (8, 8));
    assert_eq!(decoded.layout, PixelLayout::Gray8);
    // Just verify reasonable grayscale values
    assert!(decoded.pixels().iter().any(|&p| p > 200)); // white quadrant
    assert!(decoded.pixels().iter().any(|&p| p < 50));  // dark quadrants
}

#[test]
fn fixture_p3_ascii_ppm() {
    let data = fixture("p3_ascii.ppm");
    let decoded = decode(&data, Unstoppable).unwrap();
    assert_eq!((decoded.width, decoded.height), (8, 8));
    assert_eq!(decoded.layout, PixelLayout::Rgb8);
    // P3 and P6 should produce identical pixels (same image, different encoding)
    assert_eq!(decoded.pixels(), &reference_rgb8()[..]);
}

#[test]
fn fixture_p4_binary_pbm() {
    let data = fixture("p4_binary.pbm");
    let decoded = decode(&data, Unstoppable).unwrap();
    assert_eq!((decoded.width, decoded.height), (8, 8));
    assert_eq!(decoded.layout, PixelLayout::Gray8);
    // P1 and P4 should produce identical output
    let p1 = fixture("p1_ascii.pbm");
    let p1_decoded = decode(&p1, Unstoppable).unwrap();
    assert_eq!(decoded.pixels(), p1_decoded.pixels());
}

#[test]
fn fixture_p5_binary_pgm() {
    let data = fixture("p5_binary.pgm");
    let decoded = decode(&data, Unstoppable).unwrap();
    assert_eq!((decoded.width, decoded.height), (8, 8));
    assert_eq!(decoded.layout, PixelLayout::Gray8);
    // P2 and P5 should produce identical output
    let p2 = fixture("p2_ascii.pgm");
    let p2_decoded = decode(&p2, Unstoppable).unwrap();
    assert_eq!(decoded.pixels(), p2_decoded.pixels());
}

#[test]
fn fixture_p6_binary_ppm() {
    let data = fixture("p6_binary.ppm");
    let decoded = decode(&data, Unstoppable).unwrap();
    assert_eq!((decoded.width, decoded.height), (8, 8));
    assert_eq!(decoded.layout, PixelLayout::Rgb8);
    // Verify known quadrant colors: top-left should be red (255,0,0)
    let px = decoded.pixels();
    assert_eq!(&px[0..3], &[255, 0, 0]); // top-left = red
}

// ══════════════════════════════════════════════════════════════════════
// BMP
// ══════════════════════════════════════════════════════════════════════

#[cfg(feature = "bmp")]
#[test]
fn fixture_bmp_rgb24() {
    let data = fixture("rgb24.bmp");
    let decoded = decode_bmp(&data, Unstoppable).unwrap();
    assert_eq!((decoded.width, decoded.height), (8, 8));
    // BMP should match P6 reference exactly
    assert_eq!(decoded.pixels(), &reference_rgb8()[..]);
}

#[cfg(feature = "bmp")]
#[test]
fn fixture_bmp_rgba32() {
    let data = fixture("rgba32.bmp");
    let decoded = decode_bmp(&data, Unstoppable).unwrap();
    assert_eq!((decoded.width, decoded.height), (8, 8));
}

// ══════════════════════════════════════════════════════════════════════
// Farbfeld, QOI — generated by our own encoder, exact match expected
// ══════════════════════════════════════════════════════════════════════

#[test]
fn fixture_farbfeld() {
    let data = fixture("rgba16.ff");
    assert_eq!(&data[..8], b"farbfeld");
    let decoded = decode_farbfeld(&data, Unstoppable).unwrap();
    assert_eq!((decoded.width, decoded.height), (8, 8));
    assert_eq!(decoded.layout, PixelLayout::Rgba16);
}

#[cfg(feature = "qoi")]
#[test]
fn fixture_qoi() {
    let data = fixture("rgb8.qoi");
    assert_eq!(&data[..4], b"qoif");
    let decoded = decode_qoi(&data, Unstoppable).unwrap();
    assert_eq!((decoded.width, decoded.height), (8, 8));
    assert_eq!(decoded.layout, PixelLayout::Rgb8);
    assert_eq!(decoded.pixels(), &reference_rgb8()[..]);
}

// ══════════════════════════════════════════════════════════════════════
// TGA — ImageMagick-generated, may have colorspace differences
// ══════════════════════════════════════════════════════════════════════

#[cfg(feature = "tga")]
#[test]
fn fixture_tga_rgb24() {
    let data = fixture("rgb24.tga");
    let decoded = decode_tga(&data, Unstoppable).unwrap();
    assert_eq!((decoded.width, decoded.height), (8, 8));
    // IM may produce color-mapped (type 1) TGA, verify decode succeeds
    assert!(decoded.pixels().len() >= 8 * 8 * decoded.layout.bytes_per_pixel());
}

#[cfg(feature = "tga")]
#[test]
fn fixture_tga_rgba32() {
    let data = fixture("rgba32.tga");
    let decoded = decode_tga(&data, Unstoppable).unwrap();
    assert_eq!((decoded.width, decoded.height), (8, 8));
}

#[cfg(feature = "tga")]
#[test]
fn fixture_tga_gray8() {
    let data = fixture("gray8.tga");
    let decoded = decode_tga(&data, Unstoppable).unwrap();
    assert_eq!((decoded.width, decoded.height), (8, 8));
    assert_eq!(decoded.layout, PixelLayout::Gray8);
}

// ══════════════════════════════════════════════════════════════════════
// HDR — lossy RGBE, verify within tolerance
// ══════════════════════════════════════════════════════════════════════

#[cfg(feature = "hdr")]
#[test]
fn fixture_hdr() {
    let data = fixture("float.hdr");
    assert!(data.starts_with(b"#?R"));
    let decoded = decode_hdr(&data, Unstoppable).unwrap();
    assert_eq!((decoded.width, decoded.height), (8, 8));
    assert_eq!(decoded.layout, PixelLayout::RgbF32);
    // Verify top-left pixel is red-ish (R high, G/B low)
    let px = decoded.pixels();
    let r = f32::from_le_bytes(px[0..4].try_into().unwrap());
    let g = f32::from_le_bytes(px[4..8].try_into().unwrap());
    assert!(r > g, "top-left should be red: r={r}, g={g}");
}

// ══════════════════════════════════════════════════════════════════════
// Format detection on all fixtures
// ══════════════════════════════════════════════════════════════════════

#[test]
fn all_pnm_fixtures_detected() {
    assert_eq!(detect_format(&fixture("p1_ascii.pbm")), Some(ImageFormat::Pnm));
    assert_eq!(detect_format(&fixture("p2_ascii.pgm")), Some(ImageFormat::Pnm));
    assert_eq!(detect_format(&fixture("p3_ascii.ppm")), Some(ImageFormat::Pnm));
    assert_eq!(detect_format(&fixture("p4_binary.pbm")), Some(ImageFormat::Pnm));
    assert_eq!(detect_format(&fixture("p5_binary.pgm")), Some(ImageFormat::Pnm));
    assert_eq!(detect_format(&fixture("p6_binary.ppm")), Some(ImageFormat::Pnm));
}

#[cfg(feature = "bmp")]
#[test]
fn bmp_fixtures_detected() {
    assert_eq!(detect_format(&fixture("rgb24.bmp")), Some(ImageFormat::Bmp));
    assert_eq!(detect_format(&fixture("rgba32.bmp")), Some(ImageFormat::Bmp));
}
